# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#welcome'
    weight: 10
  - name: Schedule
    url: agenda/
    weight: 20
  - name: Participants
    url: '#participants'
    weight: 30
  - name: Objectives
    url: '#objectives'
    weight: 40
  - name: Organizers
    url: '#organizers'
    weight: 50
